name: "Wyoming Arabic ASR"
version: "1.0.0"
slug: "wyoming_arabic_asr"
description: "Arabic Speech Recognition for Home Assistant"
url: "https://github.com/your-username/wyoming-arabic-asr"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
map:
  - "share:rw"
options:
  uri: "tcp://0.0.0.0:10305"
  device: "cpu"
  debug: false
schema:
  uri: "str"
  device: "list(cpu|cuda)"
  debug: "bool"
ports:
  10305/tcp: 10305
startup: services
boot: auto